"""
Pydantic models for API request and response validation.
"""
from pydantic import BaseModel, Field
from typing import List

# The data structure that the user must send to the endpoint
class EvaluationRequest(BaseModel):
    query: str = Field(..., description="Real question from user")
    retrieved_context: str = Field(..., description="Context that retrieve from Vector DB")
    model_answer: str = Field(..., description="Answer that generated by AI/RAG System")

# The data structure for claim hallucination
class CritiqueDetail(BaseModel):
    claim: str
    is_supported: bool
    reason: str

# Response model
class EvaluationResponse(BaseModel):
    hallucination_score: float
    evaluation_status: str
    unsupported_claims: List[CritiqueDetail]
    suggestions: List[str]