"""
State definition for the Multi-Agent LangGraph workflow.
This acts as the shared memory/whiteboard for all agents during a single execution.
"""
from typing import TypedDict, List, Dict, Any, Optional

class EvaluationState(TypedDict):
    # Inputs from the User (The system being evaluated)
    query: str
    retrieved_context: str
    model_answer: str
    
    # Outputs generated by the Reasoning Agent
    extracted_claims: List[str]
    
    # Outputs generated by the Critic Agent
    critique_results: List[Dict[str, Any]]  # Example: [{"claim": "...", "is_supported": False, "reason": "..."}]
    
    # Outputs generated by the Evaluator Agent
    hallucination_score: Optional[float]
    evaluation_status: str # "PASS", "FAIL", or "NEEDS_REFLECTION"
    
    # Outputs generated by the Suggestion Agent
    suggestions: List[str]
    
    # Graph routing state
    current_step: str

